# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  dotnet3:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
  go:
    docker:
      - image: circleci/golang


jobs:
  build-singlepackage:
    executor: dotnet3
    steps:
      - checkout
      - run: |
          VERSION=${CIRCLE_TAG:=$(git tag).$(date '+%m%d')}
          mkdir artifacts
          echo $VERSION > artifacts/version.txt
          dotnet publish -c Release -o artifacts --no-self-contained -p:PublishSingleFile=true /p:AssemblyVersion=${VERSION:=0.0.1}
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - ./SteamLobbist.exe
            - ./version.txt
  upload-github:
    executor: go
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: |
          go get github.com/tcnksm/ghr
          VERSION=$(cat artifacts/version.txt)
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/SteamLobbist.exe
      - store_artifacts:
          path: ./artifacts

workflows:
  build-and-push:
    jobs:
      - build-singlepackage
      - upload-github
           
