# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  dotnet3:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      NUGET_XMLDOC_MODE: skip
  go:
    docker:
      - image: circleci/golang


jobs:
  build-singlepackage:
    executor: dotnet3
    steps:
      - checkout
      - run: dotnet publish -c Release -o artifacts --no-self-contained /p:AssemblyVersion=${CIRCLE_TAG:=$(git tag).$(date '+%m%d')} -p:PublishSingleFile=true
      - persist_to_workspace:
          root: .
          paths:
            - ./artifacts
  upload-github:
    executor: go
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG:=$(git tag).$(date '+%m%d')} ./artifacts/
      - store_artifacts:
          path: ./artifacts

workflows:
  build-and-push:
    jobs:
      - build-singlepackage
      - upload-github
           