# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  dotnet3:
    docker:
      - image: circleci/windows@5.0.0
  go:
    docker:
      - image: cimg/go:1.18.0


jobs:
  build-singlepackage:
    executor: dotnet3
    steps:
      - checkout
      - run:
          command: |
            VERSION=${CIRCLE_TAG:=$(git tag).$(date '+%m%d')}
            mkdir releases
            echo $VERSION > releases/version.txt
            dotnet publish -c Release -o ./releases --no-self-contained -p:PublishSingleFile=true /p:AssemblyVersion=${VERSION:=0.0.1}
          shell: bash.exe
      - persist_to_workspace:
          root: .
          paths:
            - ./releases
  upload-github:
    executor: go
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: |
          go get github.com/tcnksm/ghr
          VERSION=$(cat artifacts/releases/version.txt)
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/releases/*.exe
      - store_artifacts:
          path: ./artifacts/releases

workflows:
  build-and-push:
    jobs:
      - build-singlepackage
      - upload-github:
          requires:
            - build-singlepackage

